/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RegistrationImport } from './routes/registration'
import { Route as IndexImport } from './routes/index'
import { Route as HomeIndexImport } from './routes/home/index'
import { Route as CandidatesIndexImport } from './routes/candidates/index'
import { Route as HomeIdImport } from './routes/home/$id'
import { Route as DemoTanstackQueryImport } from './routes/demo.tanstack-query'
import { Route as DemoClerkImport } from './routes/demo.clerk'

// Create/Update Routes

const RegistrationRoute = RegistrationImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const HomeIndexRoute = HomeIndexImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRoute,
} as any)

const CandidatesIndexRoute = CandidatesIndexImport.update({
  id: '/candidates/',
  path: '/candidates/',
  getParentRoute: () => rootRoute,
} as any)

const HomeIdRoute = HomeIdImport.update({
  id: '/home/$id',
  path: '/home/$id',
  getParentRoute: () => rootRoute,
} as any)

const DemoTanstackQueryRoute = DemoTanstackQueryImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRoute,
} as any)

const DemoClerkRoute = DemoClerkImport.update({
  id: '/demo/clerk',
  path: '/demo/clerk',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/registration': {
      id: '/registration'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof RegistrationImport
      parentRoute: typeof rootRoute
    }
    '/demo/clerk': {
      id: '/demo/clerk'
      path: '/demo/clerk'
      fullPath: '/demo/clerk'
      preLoaderRoute: typeof DemoClerkImport
      parentRoute: typeof rootRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryImport
      parentRoute: typeof rootRoute
    }
    '/home/$id': {
      id: '/home/$id'
      path: '/home/$id'
      fullPath: '/home/$id'
      preLoaderRoute: typeof HomeIdImport
      parentRoute: typeof rootRoute
    }
    '/candidates/': {
      id: '/candidates/'
      path: '/candidates'
      fullPath: '/candidates'
      preLoaderRoute: typeof CandidatesIndexImport
      parentRoute: typeof rootRoute
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/registration': typeof RegistrationRoute
  '/demo/clerk': typeof DemoClerkRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/home/$id': typeof HomeIdRoute
  '/candidates': typeof CandidatesIndexRoute
  '/home': typeof HomeIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/registration': typeof RegistrationRoute
  '/demo/clerk': typeof DemoClerkRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/home/$id': typeof HomeIdRoute
  '/candidates': typeof CandidatesIndexRoute
  '/home': typeof HomeIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/registration': typeof RegistrationRoute
  '/demo/clerk': typeof DemoClerkRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/home/$id': typeof HomeIdRoute
  '/candidates/': typeof CandidatesIndexRoute
  '/home/': typeof HomeIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/registration'
    | '/demo/clerk'
    | '/demo/tanstack-query'
    | '/home/$id'
    | '/candidates'
    | '/home'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/registration'
    | '/demo/clerk'
    | '/demo/tanstack-query'
    | '/home/$id'
    | '/candidates'
    | '/home'
  id:
    | '__root__'
    | '/'
    | '/registration'
    | '/demo/clerk'
    | '/demo/tanstack-query'
    | '/home/$id'
    | '/candidates/'
    | '/home/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RegistrationRoute: typeof RegistrationRoute
  DemoClerkRoute: typeof DemoClerkRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  HomeIdRoute: typeof HomeIdRoute
  CandidatesIndexRoute: typeof CandidatesIndexRoute
  HomeIndexRoute: typeof HomeIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RegistrationRoute: RegistrationRoute,
  DemoClerkRoute: DemoClerkRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  HomeIdRoute: HomeIdRoute,
  CandidatesIndexRoute: CandidatesIndexRoute,
  HomeIndexRoute: HomeIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/registration",
        "/demo/clerk",
        "/demo/tanstack-query",
        "/home/$id",
        "/candidates/",
        "/home/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/registration": {
      "filePath": "registration.tsx"
    },
    "/demo/clerk": {
      "filePath": "demo.clerk.tsx"
    },
    "/demo/tanstack-query": {
      "filePath": "demo.tanstack-query.tsx"
    },
    "/home/$id": {
      "filePath": "home/$id.tsx"
    },
    "/candidates/": {
      "filePath": "candidates/index.tsx"
    },
    "/home/": {
      "filePath": "home/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
